### ISSUE TITLE
CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by VuManhHung97** [android/camera-samples#101]
I got this error when using cameraX. Can anybody tell me how to solve it? .thank you
``2019-11-08 13:42:07.485 15658-15692/com.example.scancamera E/Camera: Error observed on open (or opening) camera device 0: ERROR_CAMERA_SERVICE
2019-11-08 13:42:07.492 15658-15692/com.example.scancamera E/CameraCaptureSession: Session 48: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2219)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1003)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:394)
        at androidx.camera.camera2.impl.CaptureSession.release(CaptureSession.java:364)
        at androidx.camera.camera2.impl.Camera.releaseSession(Camera.java:388)
        at androidx.camera.camera2.impl.Camera.resetCaptureSession(Camera.java:901)
        at androidx.camera.camera2.impl.Camera.closeCamera(Camera.java:381)
        at androidx.camera.camera2.impl.Camera$StateCallback.handleErrorOnOpen(Camera.java:1264)
        at androidx.camera.camera2.impl.Camera$StateCallback.onError(Camera.java:1233)
        at androidx.camera.core.CameraDeviceStateCallbacks$ComboDeviceStateCallback.onError(CameraDeviceStateCallbacks.java:121)
        at android.hardware.camera2.impl.CameraDeviceImpl$11.run(CameraDeviceImpl.java:2251)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)``

**Comment by owahltinez** [comment]
Hi @VuManhHung97 , are you modifying the sample in any way? If you are, the proper place to report CameraX issues is at https://issuetracker.google.com under the Camera component. We only use this repo to track problems with the sample itself, not the library.
