### ISSUE TITLE
How to get a bitmap by takePicture ?

### ISSUE THREAD

**Issue by lijialiang** [android/camera-samples#107]
I tried to get the bitmap in the following way, but there will be a crash error.

**code**
```
imageCapture?.takePicture(executor, object : ImageCapture.OnImageCapturedListener() {
    override fun onCaptureSuccess(image: ImageProxy?, rotationDegrees: Int) {
        super.onCaptureSuccess(image, rotationDegrees)
        imageProxyToBitmap(image!!.planes[0].buffer)
    }
})
```

**crash error**
```
java.lang.IllegalStateException: Image is already closed
        at android.media.Image.throwISEIfImageIsInvalid(Image.java:72)
        at android.media.ImageReader$SurfaceImage$SurfacePlane.getBuffer(ImageReader.java:965)
        at androidx.camera.core.AndroidImageProxy$PlaneProxy.getBuffer(AndroidImageProxy.java:141)
        at com.fimo.camera.page.camera.CameraFragment$takePhoto$1$onCaptureSuccess$1.run(CameraFragment.kt:335)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

```
implementation "androidx.camera:camera-core:1.0.0-alpha06"
implementation "androidx.camera:camera-camera2:1.0.0-alpha06"
implementation "androidx.camera:camera-view:1.0.0-alpha03"
```

waiting for your reply, thank you :)

**Comment by owahltinez** [comment]
Hi @lijialiang, this repo is used to report issues with the sample itself. Since your question is about how to use the library, I would recommend using one of the following resources:

- StackOverflow (use tag `android-camerax`)
- https://g.co/camerax/developers
- https://issuetracker.google.com
