### ISSUE TITLE
java.lang.IllegalStateException: onError() should not be possible from state: INITIALIZED

### ISSUE THREAD

**Issue by NateBarak** [android/camera-samples#158]
A couple of my users got the following error:

```
java.lang.IllegalStateException: onError() should not be possible from state: INITIALIZED
	 at androidx.camera.camera2.impl.Camera$StateCallback.onError(Camera.java:1236)
	 at androidx.camera.core.CameraDeviceStateCallbacks$ComboDeviceStateCallback.onError(CameraDeviceStateCallbacks.java:121)
	 at android.hardware.camera2.impl.CameraDeviceImpl$8.run(CameraDeviceImpl.java:353)
	 at android.os.Handler.handleCallback(Handler.java:873)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loop(Looper.java:214)
	 at android.os.HandlerThread.run(HandlerThread.java:65)
```

Any idea why it happens or how I can handle such error ?
Thanks!

**Comment by owahltinez** [comment]
Hi @NateBarak! This repo is used to keep track of issues with the sample. For issues with the CameraX library or questions about how to use it, please use the tag `android-camerax` on StackOverflow, file an issue under the camera component in our [issue tracker](https://issuetracker.google.com/) or join the [developer forums](g.co/camerax/developers).
