### ISSUE TITLE
Crash on app restarted

### ISSUE THREAD

**Issue by gTisca** [android/camera-samples#202]
App crashes when I put it in background and open back quickly. 
Device: Huawei MediaPad M5 (SHT-W09)
Android Version: 8.0.0

Log: 
`E/Legacy-CameraDevice-JNI: getNativeWindow: Surface had no valid native window.
2020-04-12 23:14:20.399 12847-12889/? E/Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeDetectSurfaceDimens: Could not retrieve native window from surface.
2020-04-12 23:14:20.403 12847-12889/? E/AndroidRuntime: FATAL EXCEPTION: CameraX-
    Process: com.android.example.cameraxbasic, PID: 12847
    java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unknown error -22
        at androidx.camera.camera2.internal.Camera2CameraImpl$3.onFailure(Camera2CameraImpl.java:869)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:338)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.UnsupportedOperationException: Unknown error -22
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:77)
        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:583)
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:68)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:216)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:101)
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompatApi26Impl.<init>(OutputConfigurationCompatApi26Impl.java:42)
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompat.<init>(OutputConfigurationCompat.java:53)
        at androidx.camera.camera2.internal.CaptureSession.openCaptureSessionLocked(CaptureSession.java:373)
        at androidx.camera.camera2.internal.CaptureSession.lambda$openCaptureSession$2$CaptureSession(CaptureSession.java:281)
        at androidx.camera.camera2.internal.-$$Lambda$CaptureSession$bwwGuGuBhJx-fgB4Br9Wswwme0U.attachCompleter(Unknown Source:8)
        at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102)
        at androidx.camera.camera2.internal.CaptureSession.openCaptureSession(CaptureSession.java:278)
        at androidx.camera.camera2.internal.CaptureSession.lambda$open$0$CaptureSession(CaptureSession.java:242)
        at androidx.camera.camera2.internal.-$$Lambda$CaptureSession$2IbSQd39wMeo2dJgmFG1rvePLoM.apply(Unknown Source:8)
        at androidx.camera.core.impl.utils.futures.ChainingListenableFuture.run(ChainingListenableFuture.java:201)
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) `

**Comment by owahltinez** [comment]
Thanks for reporting this @gTisca. It looks like a library issue, and there's already a bug in the [Android component](https://issuetracker.google.com/issues/153680183). Let's track this issue there, and if it turns out to be a sample issue we can reopen this one.
