### ISSUE TITLE
Pixel-4 crashes when I click the record button.

### ISSUE THREAD

**Issue by OCEO-YJ** [android/camera-samples#208]
Everything is compiled well and I can run the app perfectly. However, when I click the record button to start, the video stops. So, after I click the stop button, then the app crashes immediately. I tried to run it on virtual pixel 3 phone, but it worked well. Also, one of my friend's phone pixel4 works well, but I cannot figure out why my phone does not work.

What I have tried so far is that, removed all the data in my pixel phone(factory version) 
I re-installed android studio, I updated os latest version. 
Even I fixed the deprecated code, however, original one and fixed one both did not work and had same error. 

```java

04/19 22:38:44: Launching 'Application' on Google Pixel 4.
$ adb shell am start -n "com.example.android.camera2video/com.example.android.camera2video.CameraActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 19686 on device 'google-pixel_4-98181FFAZ0057S'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/id.camera2vide: Late-enabling -Xcheck:jni
E/id.camera2vide: Unknown bits set in runtime_flags: 0x8000
I/id.camera2vide: The ClassLoaderContext is a special shared library.
I/Adreno: QUALCOMM build                   : 9b214d0, Ibc75db1fca
    Build Date                       : 06/30/19
    OpenGL ES Shader Compiler Version: EV031.26.06.00
    Local Branch                     : AU124
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S P 8.0.6 AArch64
I/Adreno: PFP: 0x016ee185, ME: 0x00000000
D/Camera2VideoFragment: tryAcquire
I/CameraManagerGlobal: Connecting to camera service
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
I/Choreographer: Skipped 62 frames!  The application may be doing too much work on its main thread.
E/MediaRecorder: stop failed: -1007
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.camera2video, PID: 19686
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at com.example.android.camera2video.Camera2VideoFragment.stopRecordingVideo(Camera2VideoFragment.java:682)
        at com.example.android.camera2video.Camera2VideoFragment.onClick(Camera2VideoFragment.java:312)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27881)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 19686 SIG: 9
```
Here is my stack trace. Thank you!

**Comment by owahltinez** [comment]
Thanks for reporting! The video sample was just updated and it should work on Pixel 4 devices. Please reopen if that's not the case.
