### ISSUE TITLE
NVIDIA Shield Tablet K1 - Invalid surface (black screen)

### ISSUE THREAD

**Issue by bediaz** [android/camera-samples#250]
Please follow the following instructions before filing a bug:

Execution:
Deploy CameraXBasic (Kotlin) to NVDIA Shield Tablet K1

Expected Result:
Preview will appear

Actual Result:
Black screen where camera preview should be.

Project: CameraXBasic (Kotlin)
Device Model: SHIELD Tablet K1
Build: Android 7.0
Logcat: [logcat_nvidia_shield_tablet_k1.txt](https://github.com/android/camera-samples/files/4703861/stacktrace.txt)

```
2020-05-29 13:23:19.333 7148-7168/com.android.example.cameraxbasic D/Camera: Use cases [Preview:androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, ImageAnalysis:androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, ImageCapture:androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] now ONLINE for camera 0
2020-05-29 13:23:19.333 7148-7168/com.android.example.cameraxbasic D/UseCaseAttachState: Active and online use case: [androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] for camera: 0
2020-05-29 13:23:19.334 7148-7168/com.android.example.cameraxbasic D/Camera: Resetting Capture Session
2020-05-29 13:23:19.334 7148-7168/com.android.example.cameraxbasic D/Camera: releasing session in state INITIALIZED
2020-05-29 13:23:19.334 7148-7168/com.android.example.cameraxbasic D/Camera: Transitioning camera internal state: INITIALIZED --> OPENING
2020-05-29 13:23:19.334 7148-7168/com.android.example.cameraxbasic D/Camera: Opening camera: 0
2020-05-29 13:23:19.334 7148-7168/com.android.example.cameraxbasic D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] for camera: 0
2020-05-29 13:23:19.362 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface created.
2020-05-29 13:23:19.362 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface changed. Size: 1920x1080
2020-05-29 13:23:19.635 7148-7168/com.android.example.cameraxbasic D/Camera: CameraDevice.onOpened(): 0
2020-05-29 13:23:19.636 7148-7168/com.android.example.cameraxbasic D/Camera: Transitioning camera internal state: OPENING --> OPENED
2020-05-29 13:23:19.636 7148-7168/com.android.example.cameraxbasic D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] for camera: 0
2020-05-29 13:23:19.637 7148-7168/com.android.example.cameraxbasic D/CaptureSession: Some surfaces were closed.
2020-05-29 13:23:19.638 7148-7168/com.android.example.cameraxbasic D/Camera: Posting surface closed
    java.lang.Throwable
        at androidx.camera.camera2.internal.Camera2CameraImpl.postSurfaceClosedError(Camera2CameraImpl.java:920)
        at androidx.camera.camera2.internal.Camera2CameraImpl$3.onFailure(Camera2CameraImpl.java:861)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:338)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2020-05-29 13:23:19.639 7148-7168/com.android.example.cameraxbasic D/Camera: Use case Preview:androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7 RESET for camera 0
2020-05-29 13:23:19.639 7148-7168/com.android.example.cameraxbasic D/Camera: Resetting Capture Session
2020-05-29 13:23:19.639 7148-7168/com.android.example.cameraxbasic D/Camera: releasing session in state OPENED
2020-05-29 13:23:19.640 7148-7168/com.android.example.cameraxbasic D/UseCaseAttachState: Active and online use case: [androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] for camera: 0
2020-05-29 13:23:19.640 7148-7168/com.android.example.cameraxbasic D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-eb3ed620-bd7c-4a0a-a79c-6938f41173b7, androidx.camera.core.ImageAnalysis-c6602c61-6df1-4de1-bb1d-0036d5171201, androidx.camera.core.ImageCapture-4e769e88-ab5a-490b-a8b8-4de4a76a2705] for camera: 0
2020-05-29 13:23:19.643 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface destroyed.
2020-05-29 13:23:19.667 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface created.
2020-05-29 13:23:19.668 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface changed. Size: 1920x1080
2020-05-29 13:23:19.669 7148-7148/com.android.example.cameraxbasic D/SurfaceViewImpl: Surface set on Preview.
2020-05-29 13:23:19.670 7148-7168/com.android.example.cameraxbasic D/CaptureSession: Opening capture session.
2020-05-29 13:23:19.725 7148-7168/com.android.example.cameraxbasic D/CaptureSession: Attempting to send capture request onConfigured
2020-05-29 13:23:19.725 7148-7168/com.android.example.cameraxbasic D/CaptureSession: Issuing request for session.
2020-05-29 13:23:19.727 7148-7168/com.android.example.cameraxbasic D/CaptureSession: CameraCaptureSession.onConfigured() mState=OPENED
2020-05-29 13:23:19.727 7148-7168/com.android.example.cameraxbasic D/CaptureSession: CameraCaptureSession.onReady() OPENED
2020-05-29 13:23:19.960 7148-7159/com.android.example.cameraxbasic I/art: Background partial concurrent mark sweep GC freed 557(16KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 8MB/14MB, paused 11.111ms total 43.356ms
2020-05-29 13:23:20.001 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 18.07187934027778
2020-05-29 13:23:20.078 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 18.033995225694444
2020-05-29 13:23:20.159 7148-7159/com.android.example.cameraxbasic I/art: Background sticky concurrent mark sweep GC freed 498(3MB) AllocSpace objects, 1(904KB) LOS objects, 9% free, 13MB/14MB, paused 16.031ms total 77.396ms
2020-05-29 13:23:20.167 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 4.073662109375
2020-05-29 13:23:20.224 7148-7159/com.android.example.cameraxbasic I/art: Background partial concurrent mark sweep GC freed 575(7MB) AllocSpace objects, 2(1808KB) LOS objects, 40% free, 8MB/14MB, paused 15.397ms total 53.349ms
2020-05-29 13:23:20.249 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 3.736470269097222
2020-05-29 13:23:20.311 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 3.5505327690972224
2020-05-29 13:23:20.372 7148-7233/com.android.example.cameraxbasic D/CameraXBasic: Average luminosity: 4.109060329861111
2020-05-29 13:23:20.388 7148-7159/com.android.example.cameraxbasic I/art: Background sticky concurrent mark sweep GC freed 40
```
Video:
![camerax_nvidia](https://user-images.githubusercontent.com/1886865/83297258-7a371380-a1af-11ea-813a-99306028c09e.gif)

**Comment by owahltinez** [comment]
@bediaz can you please try again now that the library has been updated to `beta04`?

**Comment by bediaz** [comment]
The beta04 library resolves the issue with the black preview! However, the preview is now stretched when in portrait. I will look into this and create a separate issue.
