### ISSUE TITLE
App crashes if I choose any resolution to record video

### ISSUE THREAD

**Issue by KarimFikani** [android/camera-samples#263]
App keeps crashing for any resolution that I choose on my device (OnePlus A6003). 

Logcat when the crash happens:

```
2020-07-03 09:59:37.288 32193-32299/com.android.example.camera2.video E/MediaRecorder: stop called in an invalid state: 4
2020-07-03 09:59:37.312 32193-32299/com.android.example.camera2.video E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.android.example.camera2.video, PID: 32193
    java.lang.IllegalStateException
        at android.media.MediaRecorder.stop(Native Method)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1$1$2.invokeSuspend(CameraFragment.kt:297)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Other errors that were captured before the crash:

```
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: Fail to get file list com.android.example.camera2.video
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: Fail to get file list com.android.example.camera2.video
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: Fail to get file list oat
2020-07-03 09:59:15.930 32193-32223/com.android.example.camera2.video E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
```

Info captured by logcat that are not errors before the crash:

```
2020-07-03 09:59:15.967 32193-32193/com.android.example.camera2.video W/e.camera2.vide: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-07-03 09:59:15.982 32193-32193/com.android.example.camera2.video V/FlingOptimizerScroller: FlingOptimizerOverScroller Init
2020-07-03 09:59:15.984 32193-32193/com.android.example.camera2.video I/CameraManagerGlobal: Connecting to camera service
2020-07-03 09:59:15.986 32193-32193/com.android.example.camera2.video W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
2020-07-03 09:59:15.986 32193-32193/com.android.example.camera2.video W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 3
2020-07-03 09:59:16.020 32193-32193/com.android.example.camera2.video V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
2020-07-03 09:59:16.030 32193-32215/com.android.example.camera2.video D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@7c785c6[CameraActivity]
2020-07-03 09:59:16.034 32193-32224/com.android.example.camera2.video I/AdrenoGLES: QUALCOMM build                   : 35556ba, I9ca166462c
    Build Date                       : 08/07/19
    OpenGL ES Shader Compiler Version: EV031.27.02.00
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-07-03 09:59:16.034 32193-32224/com.android.example.camera2.video I/AdrenoGLES: Build Config                     : S P 8.0.8 AArch64
2020-07-03 09:59:16.036 32193-32224/com.android.example.camera2.video I/AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
2020-07-03 09:59:16.069 32193-32224/com.android.example.camera2.video W/Gralloc3: mapper 3.x is not supported
2020-07-03 09:59:27.216 32193-32193/com.android.example.camera2.video I/Surface: opservice is null false
2020-07-03 09:59:33.552 32193-32193/com.android.example.camera2.video I/Surface: opservice is null false
2020-07-03 09:59:33.689 32193-32193/com.android.example.camera2.video E/SensorManager: registerListenerImpl sensorName:BMI160_ACCELEROMETER Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.android.example.camera2.video,callingPid:32193,callingUid:10443
2020-07-03 09:59:33.737 32193-32193/com.android.example.camera2.video D/CameraFragment: View finder size: 1080 x 2200
2020-07-03 09:59:33.737 32193-32193/com.android.example.camera2.video D/CameraFragment: Selected preview size: 1920x1080
2020-07-03 09:59:33.744 32193-32193/com.android.example.camera2.video D/AutoFitSurfaceView: Measured dimensions set: 1238 x 2200
2020-07-03 09:59:33.745 32193-32193/com.android.example.camera2.video I/chatty: uid=10443(com.android.example.camera2.video) identical 1 line
2020-07-03 09:59:33.746 32193-32193/com.android.example.camera2.video D/AutoFitSurfaceView: Measured dimensions set: 1238 x 2200
2020-07-03 09:59:33.745 32193-32193/com.android.example.camera2.video W/e.camera2.video: type=1400 audit(0.0:69982): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=15186 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2020-07-03 09:59:33.760 32193-32193/com.android.example.camera2.video E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
2020-07-03 09:59:33.793 32193-32193/com.android.example.camera2.video I/OMXClient: IOmx service obtained
2020-07-03 09:59:33.795 32193-32193/com.android.example.camera2.video E/SensorManager: registerListenerImpl sensorName:BMI160_ACCELEROMETER Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.android.example.camera2.video,callingPid:32193,callingUid:10443
2020-07-03 09:59:33.987 32193-32193/com.android.example.camera2.video E/SensorManager: unregisterListenerImpl callingApp: com.android.example.camera2.video,callingPid:32193,callingUid:10443
2020-07-03 09:59:34.268 32193-32193/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2020-07-03 09:59:37.232 32193-32297/com.android.example.camera2.video E/SensorManager: registerListenerImpl sensorName:BMI160_ACCELEROMETER Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.android.example.camera2.video,callingPid:32193,callingUid:10443
2020-07-03 09:59:37.288 32193-32299/com.android.example.camera2.video D/CameraFragment: Recording stopped. Output file: /data/user/0/com.android.example.camera2.video/files/VID_2020_07_03_09_59_33_816.mp4
```

So the crash always happen on recorder.stop(). Some files were saved even with a crash.

<img width="816" alt="Screen Shot 2020-07-03 at 10 12 43 AM" src="https://user-images.githubusercontent.com/2486075/86488434-d264b680-bd15-11ea-9c7a-304fad359977.png">

Info about the phone that is running the app

![image](https://user-images.githubusercontent.com/2486075/86488228-2f13a180-bd15-11ea-8e8c-f04615668a0f.png)

**Comment by KarimFikani** [comment]
Same error as #254
