### ISSUE TITLE
videoCapture

### ISSUE THREAD

**Issue by 1479HuangDa** [android/camera-samples#278]
The API for VideoCapture starting to video record is crash in version of 1.0.0-beta07 .  the log as follow:
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.AudioRecord.startRecording()' on a null object reference
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err:     at androidx.camera.core.VideoCapture.startRecording(VideoCapture.java:326)
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err:     at androidx.camera.core.VideoCapture.startRecording(VideoCapture.java:295)
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err:     at com.example.library_common.album.ui.AlbumCameraFragment.toRecordVideo(AlbumCameraFragment.kt:509)
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err:     at com.example.library_common.album.ui.AlbumCameraFragment.OnRecordStartClick(AlbumCameraFragment.kt:501)
2020-08-14 16:03:58.909 30352-30352/com.example.companycoding W/System.err:     at com.example.library_common.album.view.CameraBottomView$MHandler.handleMessage(CameraBottomView.java:621)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at android.os.Looper.loop(Looper.java:238)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7767)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-08-14 16:03:58.910 30352-30352/com.example.companycoding W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

**Comment by zakrodionov** [comment]
> void android.media.AudioRecord.startRecording()

add permission  <uses-permission android:name="android.permission.RECORD_AUDIO" /> and check it in runtime
