### ISSUE TITLE
CameraX application crashing on our company hardware . This is related to Option not found for LensFacing. 

### ISSUE THREAD

**Issue by arpitcybernetyx** [android/camera-samples#307]
Android 8 
```

09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: Unable to determine default lens facing for ImageAnalysis.
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: java.lang.IllegalArgumentException: Invalid camera: null
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.CameraRepository.getCamera(CameraRepository.java:82)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.CameraX.getCameraInfo(CameraX.java:315)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.camera2.impl.ImageAnalysisConfigProvider.getConfig(ImageAnalysisConfigProvider.java:98)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.camera2.impl.ImageAnalysisConfigProvider.getConfig(ImageAnalysisConfigProvider.java:43)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.ExtendableUseCaseConfigFactory.getConfig(ExtendableUseCaseConfigFactory.java:49)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.CameraX.getDefaultUseCaseConfig(CameraX.java:345)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.ImageAnalysis.getDefaultBuilder(ImageAnalysis.java:227)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.UseCase.updateUseCaseConfig(UseCase.java:135)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.UseCase.<init>(UseCase.java:92)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.camera.core.ImageAnalysis.<init>(ImageAnalysis.java:74)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.setImageAnalysis(MiniAugmentoKotlin.kt:347)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.startCamera(MiniAugmentoKotlin.kt:313)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.initilizeSetUp(MiniAugmentoKotlin.kt:225)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.onViewCreated(MiniAugmentoKotlin.kt:145)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.Activity.performStart(Activity.java:6995)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.os.Looper.loop(Looper.java:164)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-22 13:16:16.825 29408 29408 W ImageAnalysisProvider: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
09-22 13:16:16.836 29408 29408 D AndroidRuntime: Shutting down VM
09-22 13:16:16.840 29408 29408 E AndroidRuntime: FATAL EXCEPTION: main
09-22 13:16:16.840 29408 29408 E AndroidRuntime: Process: com.cnx.kneurateach, PID: 29408
09-22 13:16:16.840 29408 29408 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cnx.kneurateach/com.cnx.kneurateach.mini_augmento.camera_module.screens.fragments.ActCamera}: java.lang.IllegalArgumentException: Option does not exist: Option{id=camerax.core.camera.lensFacing, valueClass=class androidx.camera.core.CameraX$LensFacing, token=null}
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Option does not exist: Option{id=camerax.core.camera.lensFacing, valueClass=class androidx.camera.core.CameraX$LensFacing, token=null}
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.camera.core.OptionsBundle.retrieveOption(OptionsBundle.java:107)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.camera.core.ImageAnalysisConfig.retrieveOption(ImageAnalysisConfig.java:130)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.camera.core.CameraX.calculateSuggestedResolutions(CameraX.java:475)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:188)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.startCamera(MiniAugmentoKotlin.kt:314)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.initilizeSetUp(MiniAugmentoKotlin.kt:225)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at com.cnx.kneurateach.mini_augmento.MiniAugmentoKotlin.onViewCreated(MiniAugmentoKotlin.kt:145)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6995)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
09-22 13:16:16.840 29408 29408 E AndroidRuntime: 	... 9 more
09-22 13:16:16.860 29408 29459 W GooglePlayServicesUtil: Google Play Store is missing.
09-22 13:16:16.900  2777 27572 W ActivityManager:   Force finishing activity com.cnx.kneurateach/.mini_augmento.camera_module.screens.fragments.ActCamera
09-22 13:16:16.904  2777 27572 W ActivityManager:   Force finishing activity com.cnx.kneurateach/.dashboard.DashboardActivity
```

**Comment by owahltinez** [comment]
Sorry, given that this is custom hardware it could be many different issues. I would guess that it's related to the camera selector. Can you please send an email to g.co/camerax-developers and provide more details about the hardware? Make sure you include number of cameras, their physical configuration, whether they are considered front/back/external...
