### ISSUE TITLE
There is an error, can you give me any help

### ISSUE THREAD

**Issue by leeyf888** [android/camera-samples#309]
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: xxxl, PID: 16801
    java.lang.ArrayIndexOutOfBoundsException: length=518400; index=-1
        at com.xxxl.utils.YuvToRgbConverter.imageToByteArray(YuvToRgbConverter.kt:164)
        at com.xxx.createFile(ShootingPageFragment.kt:252)
        at com.xxx.access$createFile(ShootingPageFragment.kt:37)
        at com.xxxl.fragment.ShootingPageFragment$takePhoto$1.onCaptureSuccess(ShootingPageFragment.kt:229)
        at androidx.camera.core.ImageCapture$ImageCaptureRequest.lambda$dispatchImage$0$ImageCapture$ImageCaptureRequest(ImageCapture.java:2024)
        at androidx.camera.core.-$$Lambda$ImageCapture$ImageCaptureRequest$E13UUGhRx8PID5WbaCuwcGP87BA.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camera` in StackOverflow.
