### ISSUE TITLE
VideoCapture not working with app local file

### ISSUE THREAD

**Issue by darrinps** [android/camera-samples#357]
Running     implementation "androidx.camera:camera-core:1.1.0-alpha02"

Can work with phone's gallery just fine but when you try to use an app local file, it crashes with: 

java.lang.IllegalArgumentException: Unknown URL file:///data/user/0/com.company.appname/files/VIDEO_20210228_161139.mp4
        at android.content.ContentResolver.insert(ContentResolver.java:1831)
        at androidx.camera.core.VideoCapture.initMediaMuxer(VideoCapture.java:1025)

This same file works fine with Exoplayer for example. Just not VideoCapture when you start recording. For example:

        val outputFileOptions = VideoCapture.OutputFileOptions.Builder(
            this.contentResolver,
//            MediaStore.Video.Media.EXTERNAL_CONTENT_URI, //Use this to save in normal Gallery
            file.toUri(),
            contentValues
        ).build()

...will cause a crash

**Comment by darrinps** [comment]
Looks like you can use VideoCapture.OutputFileOptions.Builder(file).build() instead.
