### ISSUE TITLE
Camera2Video - Not Working on S21

### ISSUE THREAD

**Issue by nedols** [android/camera-samples#371]
Hi at all, 

I'm try to test the video example on my Samsung S21, but I'm facing this issue.

The issue happen when I release the capture button to stop recording.

**Step to reproduce**
> Clone the repo.
> Build and run the Camera2Video example on real device.
> Push capture button to Start recording 
> Release the capture button.

**Environment info:**
>Android Studio 4.1.3
>Build #AI-201.8743.12.41.7199119, built on March 11, 2021
>Runtime version: 1.8.0_242-release-1644-b01 amd64
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>Windows 10 10.0
>GC: ParNew, ConcurrentMarkSweep
>Memory: 1856M
>Cores: 8
>Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
>Non-Bundled Plugins: Batch Scripts Support, CMD Support, GLSL, com.easylokal.stringResourceHelper, com.thoughtworks.gauge, org.jetbrains.kotlin, com.shenyong.flutter.refgenerator, com.stardon.androiddrawable, com.chrisrm.idea.MaterialThemeUI, com.madrapps.dagger-plugin, br.com.dynamiclight.android-master-tools, drawable.importer.pluginId.7658.hack', PythonCore, Dart, io.flutter, com.localizely.flutter-intl

**Device Info:** 
>SW: Android 11
>Model: SM-G991B/DS
>BuildVersion: RP1A.200720.012.G991BXXU2AUC8
 
**Logcat Output**

`2021-04-06 14:22:58.307 18728-18728/com.android.example.camera2.video I/CameraManagerGlobal: Connecting to camera service
2021-04-06 14:22:58.310 18728-18728/com.android.example.camera2.video D/VendorTagDescriptor: addVendorDescriptor: vendor tag id 3854507339 added
2021-04-06 14:22:58.312 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.android.example.camera2.video API Level 2
2021-04-06 14:22:58.313 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.instagram.android API Level 2
2021-04-06 14:22:58.313 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 2 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.313 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 20 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.sec.android.app.camera API Level 2
2021-04-06 14:22:58.314 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 21 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.314 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 23 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.314 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 3 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.314 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 4 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.315 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 50 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:22:58.315 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 52 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
2021-04-06 14:23:14.555 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:15.665 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:16.182 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:16.301 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:18.246 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:18.479 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:18.571 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:18.830 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:24.980 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:25.091 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:25.119 18728-18728/com.android.example.camera2.video I/SurfaceView: onWindowVisibilityChanged(0) true com.example.android.camera.utils.AutoFitSurfaceView{8b9c668 V.E...... ......I. 0,0-0,0 #7f08013c app:id/view_finder} of ViewRootImpl@812c1a6[CameraActivity]
2021-04-06 14:23:25.131 18728-18728/com.android.example.camera2.video D/SensorManager: registerListener :: 1, LSM6DSO Accelerometer, 200000, 0, android.view.OrientationEventListener$SensorEventListenerImpl@a9e6fb2
2021-04-06 14:23:25.139 18728-18728/com.android.example.camera2.video I/SurfaceControl: release : mNativeObject = -5476376612989547568 - Surface(name=com.android.example.camera2.video/com.example.android.camera2.video.CameraActivity$_18728)/@0xda4f58a / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1777 android.view.ViewRootImpl.relayoutWindow:8827 
2021-04-06 14:23:25.139 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject s[-5476376612989547568]
2021-04-06 14:23:25.139 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject e[-5476376612989547568]
2021-04-06 14:23:25.140 18728-18728/com.android.example.camera2.video I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x3175f94 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1787 android.view.ViewRootImpl.relayoutWindow:8827 android.view.ViewRootImpl.performTraversals:3245 android.view.ViewRootImpl.doTraversal:2508 android.view.ViewRootImpl$TraversalRunnable.run:9784 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: release : mNativeObject = -5476376612989556304 - Surface(name=Surface(name=1398283 InputMethod)/@0xa76882c - animation-leash)/@0x7d64775 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject s[-5476376612989556304]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject e[-5476376612989556304]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: release : mNativeObject = -5476376612989550592 - Surface(name=Surface(name=5eb1699 NavigationBar0)/@0xf0d282a - animation-leash)/@0x980430a / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject s[-5476376612989550592]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject e[-5476376612989550592]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: release : mNativeObject = -5476376612989569744 - Surface(name=Surface(name=566b70 StatusBar)/@0xc62a81e - animation-leash)/@0x3c5c77b / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject s[-5476376612989569744]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/SurfaceControl: nativeRelease nativeObject e[-5476376612989569744]
2021-04-06 14:23:25.141 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: Relayout returned: old=(0,80,1080,2400) new=(0,80,1080,2400) req=(1080,2320)0 dur=6 res=0x1 s={true -5476376608157630192} ch=false fn=650
2021-04-06 14:23:25.145 18728-18728/com.android.example.camera2.video I/SurfaceView: surfaceCreated 1 #8 com.example.android.camera.utils.AutoFitSurfaceView{8b9c668 V.E...... ......ID 0,0-1080,2320 #7f08013c app:id/view_finder}
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video D/CameraFragment: View finder size: 1080 x 2320
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video D/CameraFragment: Selected preview size: 1920x1080
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video I/SurfaceView: surfaceChanged (1080,2320) 1 #8 com.example.android.camera.utils.AutoFitSurfaceView{8b9c668 V.E...... ......ID 0,0-1080,2320 #7f08013c app:id/view_finder}
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView$1.onPreDraw:225 android.view.ViewTreeObserver.dispatchOnPreDraw:1124 
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
2021-04-06 14:23:25.152 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] rdf()
2021-04-06 14:23:25.155 18728-20522/com.android.example.camera2.video I/SurfaceView: setParentSpaceRectangle: useBLAST = false position = Rect(0, 0 - 1080, 2320) frameNumber = 650 t = android.view.SurfaceControl$Transaction@21f9998
2021-04-06 14:23:25.155 18728-20522/com.android.example.camera2.video I/SurfaceView: applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@21f9998 surfaceControl = Surface(name=SurfaceView - com.android.example.camera2.video/com.example.android.camera2.video.CameraActivity@8b9c668@0)/@0xbd0e5f1 frame = 650
2021-04-06 14:23:25.156 18728-18728/com.android.example.camera2.video D/AutoFitSurfaceView: Measured dimensions set: 1305 x 2320
2021-04-06 14:23:25.156 18728-20522/com.android.example.camera2.video I/SurfaceView: applySurfaceTransforms: postScaleX = 1.0 postScaleY = 1.0
2021-04-06 14:23:25.157 18728-18728/com.android.example.camera2.video I/SurfaceView: surfaceChanged (1920,1080) 1 #5 com.example.android.camera.utils.AutoFitSurfaceView{8b9c668 V.E...... ......ID 0,0-1305,2320 #7f08013c app:id/view_finder}
2021-04-06 14:23:25.157 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView.setFrame:646 android.view.View.layout:24472 
2021-04-06 14:23:25.157 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
2021-04-06 14:23:25.157 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: [DP] rdf()
2021-04-06 14:23:25.159 18728-20521/com.android.example.camera2.video I/SurfaceView: setParentSpaceRectangle: useBLAST = false position = Rect(0, 0 - 1305, 2320) frameNumber = 651 t = android.view.SurfaceControl$Transaction@21f9998
2021-04-06 14:23:25.159 18728-20521/com.android.example.camera2.video I/SurfaceView: applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@21f9998 surfaceControl = Surface(name=SurfaceView - com.android.example.camera2.video/com.example.android.camera2.video.CameraActivity@8b9c668@0)/@0xbd0e5f1 frame = 651
2021-04-06 14:23:25.160 18728-20521/com.android.example.camera2.video I/SurfaceView: applySurfaceTransforms: postScaleX = 0.6796875 postScaleY = 2.148148
2021-04-06 14:23:25.176 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.android.example.camera2.video API Level 2
2021-04-06 14:23:25.192 18728-18728/com.android.example.camera2.video I/OMXClient: IOmx service obtained
2021-04-06 14:23:25.193 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setup
2021-04-06 14:23:25.197 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setAudioSource(1)
2021-04-06 14:23:25.205 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setVideoSource(2)
2021-04-06 14:23:25.208 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setParameter()
2021-04-06 14:23:25.208 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setVideoFrameRate(60)
2021-04-06 14:23:25.208 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setVideoSize(1920, 1080)
2021-04-06 14:23:25.208 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setVideoEncoder(2)
2021-04-06 14:23:25.209 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setAudioEncoder(3)
2021-04-06 14:23:25.209 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: android_media_MediaRecorder_setInputSurface
2021-04-06 14:23:25.209 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: get_persistentSurface
2021-04-06 14:23:25.213 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: setOutputFile
2021-04-06 14:23:25.213 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: prepare
2021-04-06 14:23:25.292 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: release
2021-04-06 14:23:25.915 18728-20374/com.android.example.camera2.video I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.android.example.camera2.video API Level 2
2021-04-06 14:23:26.249 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 270
2021-04-06 14:23:26.262 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:26.339 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 0
2021-04-06 14:23:26.363 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:27.522 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 0
2021-04-06 14:23:27.689 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:27.899 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 0
2021-04-06 14:23:27.963 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:29.499 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 0
2021-04-06 14:23:29.607 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:29.659 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 0
2021-04-06 14:23:29.695 18728-18728/com.android.example.camera2.video D/CameraFragment: Orientation changed: 90
2021-04-06 14:23:36.184 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:36.295 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:36.316 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setup
2021-04-06 14:23:36.321 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setAudioSource(1)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setVideoSource(2)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setParameter()
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setVideoFrameRate(60)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setVideoSize(1920, 1080)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setVideoEncoder(2)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setAudioEncoder(3)
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: android_media_MediaRecorder_setInputSurface
2021-04-06 14:23:36.329 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: get_persistentSurface
2021-04-06 14:23:36.333 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setParameter()
2021-04-06 14:23:36.348 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: setOutputFile
2021-04-06 14:23:36.349 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: prepare
2021-04-06 14:23:36.477 18728-20664/com.android.example.camera2.video I/MediaRecorderJNI: start
2021-04-06 14:23:36.492 18728-20664/com.android.example.camera2.video D/CameraFragment: Recording started
2021-04-06 14:23:41.071 18728-20520/com.android.example.camera2.video E/CameraFragment: Camera 0 error: (4) Fatal (device)
    java.lang.RuntimeException: Camera 0 error: (4) Fatal (device)
        at com.example.android.camera2.video.fragments.CameraFragment$openCamera$$inlined$suspendCancellableCoroutine$lambda$1.onError(CameraFragment.kt:371)
        at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1637)
        at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
        at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-04-06 14:23:44.039 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 0
2021-04-06 14:23:44.130 18728-18728/com.android.example.camera2.video I/ViewRootImpl@812c1a6[CameraActivity]: ViewPostIme pointer 1
2021-04-06 14:23:44.134 18728-18728/com.android.example.camera2.video D/CameraFragment: Recording stopped. Output file: /data/user/0/com.android.example.camera2.video/files/VID_2021_04_06_14_23_25_207.mp4
2021-04-06 14:23:44.135 18728-18728/com.android.example.camera2.video I/MediaRecorderJNI: stop
2021-04-06 14:23:45.151 18728-18728/com.android.example.camera2.video E/MediaRecorder: stop failed: -1007
2021-04-06 14:23:45.161 18728-18728/com.android.example.camera2.video E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.example.camera2.video, PID: 18728
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder._stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1501)
        at com.example.android.camera2.video.fragments.CameraFragment$stopRecording$1.invokeSuspend(CameraFragment.kt:293)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8462)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-04-06 14:23:45.204 18728-18728/com.android.example.camera2.video I/Process: Sending signal. PID: 18728 SIG: 9
`

**Comment by nedols** [comment]
I also tested the same application with a Pixel 4 running Android 11 and all works as expected.

So the issue seems to be device specific.

**Comment by nedols** [comment]
I made several test on my S21 and I found that the issue occur only when we start recording video at 60fps.

I printed the capabilities for each camera of my S21 on LogCat , seeing that 1920x1080@60fps should be supported but if i start to record with this settings the application crashes. The same for every configuration that supports 60fps.

**Comment by nedols** [comment]
Hi close this issue because is the same of #329.
