### ISSUE TITLE
MediaRecorder: stop called in an invalid state: 4

### ISSUE THREAD

**Issue by JakeWoki** [android/camera-samples#383]
```
E/MediaRecorder: stop called in an invalid state: 4
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.android.example.camera2.video, PID: 10071
    java.lang.IllegalStateException
        at android.media.MediaRecorder.native_stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1901)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1$1$2.invokeSuspend(CameraFragment.kt:297)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Step to reproduce

```
Clone the repo.
Build and run the Camera2Video example on real device.
Push capture button to Start recording
Release the capture button.
```
Environment info:
```
Android Studio 4.2
Windows 10
```
Device Info:
```
Android 10
HONOR  OXF-AN10
4.0.0.174
```

**Comment by JakeWoki** [comment]
https://github.com/android/camera-samples/issues/254
