### ISSUE TITLE
CameraX:No available camera can be found.

### ISSUE THREAD

**Issue by yonglf** [android/camera-samples#415]
E/CameraManager: Failed to parse camera Id /dev/video0 to integer
D/CameraRepository: Added camera: /dev/video0
W/Camera2CamcorderProfileProvider: Camera id is not an integer: /dev/video0, unable to create CamcorderProfileProvider
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraValidator: Verifying camera lens facing on pad, lensFacingInteger: null
E/CameraValidator: Camera LensFacing verification failed, existing cameras: [Camera@75e5ee1[id=/dev/video0]]
W/CameraX: Retry init. Start time 102582 current time 104905
    androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
        at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:95)
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX(CameraX.java:613)
        at androidx.camera.core.-$$Lambda$CameraX$u-Xx2b6YXY5GXNXRh-mDiDnHdpQ.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: No available camera can be found.
        at androidx.camera.core.CameraSelector.filter(CameraSelector.java:105)
        at androidx.camera.core.CameraSelector.filter(CameraSelector.java:135)
        at androidx.camera.core.CameraSelector.select(CameraSelector.java:75)
        at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:81)
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX(CameraX.java:613) 
        at androidx.camera.core.-$$Lambda$CameraX$u-Xx2b6YXY5GXNXRh-mDiDnHdpQ.run(Unknown Source:10) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by PixsaOJ** [comment]
I am on LineageOS, after 4 days of update on April 18 all my camera apps stopped working.

I have same error logs. I do not think this issue is for this repository tho.
