### ISSUE TITLE
CameraX crash and functionality additions

### ISSUE THREAD

**Issue by Office-Murtaza** [android/camera-samples#437]
cameraX crash on  small resolution which return empty list of camera selectors. how to get current resolution of current device resolution. Switch back camera while camera in a pause or how to switch to back camera while recording from camera .
Sorry for english mistakes.

Also crash on QMobile s6 android version 6.0  when we request camera QualitySelector.QUALITY_HIGHEST and QualitySelector.QUALITY_LOWEST because no other QualitySelector return by Camera HardWare.

Crash:
java.lang.IllegalStateException: Surface was requested when the Recorder had encountered error androidx.camera.video.internal.encoder.InvalidConfigException: Encoder cannot created: null
        at androidx.camera.video.Recorder.onSurfaceRequested(Recorder.java:414)
        at androidx.camera.video.VideoCapture.createPipeline(VideoCapture.java:388)
        at androidx.camera.video.VideoCapture.resetPipeline(VideoCapture.java:435)
        at androidx.camera.video.VideoCapture.lambda$createPipeline$0$VideoCapture(VideoCapture.java:403)
        at androidx.camera.video.-$$Lambda$VideoCapture$6BBmhv2eFVUcrkw2nD0ve39oNMM.onError(lambda)
        at androidx.camera.camera2.internal.Camera2CameraImpl.lambda$postSurfaceClosedError$13(Camera2CameraImpl.java:1153)
        at androidx.camera.camera2.internal.-$$Lambda$Camera2CameraImpl$EQgjyk5vUNeY9hNKpGr93fYzUDE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by ggfan** [comment]
If there is no supported camera selectors, the sample exits ( could not continue ).  To get the resolution of the the selected QualitySelector, use [QualitySelector.getResolution()](https://developer.android.com/reference/androidx/camera/video/QualitySelector#getResolution(androidx.camera.core.CameraInfo,%20int)) after binding so you have the selected camera, and its CameraInfo. It is not supported to switching camera at run-time while capturing has started, but the feature is on the future release plan. 

Do the above answer your questions?

**Comment by ggfan** [comment]
Hey @Office-Murtaza, may you kindly create a ticket [here](https://issuetracker.google.com/issues/new?component=618491&template=1257717) so we we could follow up more with the issue? thank you!
