### ISSUE TITLE
CameraXVideo sample not recording video.

### ISSUE THREAD

**Issue by Office-Murtaza** [android/camera-samples#462]
Camera Surface is created by camera but not recording video. No video recording statistics start . Below crash occure while stop recording. 
Device info:: Galaxy Tab A(2016),model SM-T285, Android Version 5.1.1

2022-01-18 11:24:28.410 10840-10937/com.android.example.camerax.video E/AndroidRuntime: FATAL EXCEPTION: CameraX-camerax_io_0
    Process: com.android.example.camerax.video, PID: 10840
  java.lang.AssertionError: Incorrectly invoke onInitialized() in state IDLING
        at androidx.camera.video.Recorder.onInitialized(Recorder.java:987)
        at androidx.camera.video.Recorder.lambda$setupVideo$12$Recorder(Recorder.java:1230)
        at androidx.camera.video.Recorder$$ExternalSyntheticLambda7.onSurfaceUpdate(Unknown Source)
        at androidx.camera.video.internal.encoder.EncoderImpl$SurfaceInput.lambda$notifySurfaceUpdate$0(EncoderImpl.java:1191)
        at androidx.camera.video.internal.encoder.EncoderImpl$SurfaceInput$$ExternalSyntheticLambda0.run(Unknown Source)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$1.run(SequentialExecutor.java:111)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by Office-Murtaza** [comment]
The latest update of CamerXVideo does not have the above issue.
