### ISSUE TITLE
java.lang.IllegalStateException: Detaching occurs more times than attaching

### ISSUE THREAD

**Issue by aqsaShahid-zameen** [android/camera-samples#89]
This is my Logcat
  at androidx.camera.core.DeferrableSurface.notifySurfaceDetached(DeferrableSurface.java:160)
        at androidx.camera.camera2.impl.Camera.notifyDetachFromUseCaseSurfaces(Camera.java:667)
        at androidx.camera.camera2.impl.Camera.removeOnlineUseCase(Camera.java:789)
        at androidx.camera.camera2.impl.Camera$13.run(Camera.java:772)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
Everything was working fine(except on few devices) before updated and then I updated to cameraX alpha-006 and now I am getting this error.
Any idea how this is going to get fixed?
Any help will be appreciated.

**Comment by aqsaShahid-zameen** [comment]
I think the bug was on my end as i was extending fragment from Executor and using the same thread over and over again whereas now I have created a new executor for everytime the ImageCapture is called and that has pretty much fixed it.

**Comment by owahltinez** [comment]
What sample are you seeing this in? What device produces this error? Have you modified the sample in any way?

**Comment by aqsaShahid-zameen** [comment]
I have updated camerax to alpha-006.

**Comment by owahltinez** [comment]
If you are modifying the sample, then it's not a sample issue. Please use the Camera component under https://issuetracker.google.com
